title: "【実践】エンジニアの基礎教養-アルゴリズムを学べる本"
summary: 
  "筆者は新卒エンジニア時代に社内でアルゴリズム勉強会を主催していました。\n
  その内容を本形式に書き起こしたものになります。\n

  【この本の特徴】\n
  📗問題演習形式でアルゴリズムの基礎が身に付く構成となっています。\n
  📗分かりにくい概念は丁寧に図解で解説しています。\n
  📗基礎的なアルゴリズムがどのように世の中に役立っているのかを言及しています。\n

  アルゴリズムに関して、皆さんの理解を深めるお手伝いができれば幸いです。
  
  "
topics: ["アルゴリズム", "勉強会", "Python", "競技プログラミング", "新卒"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - introduction
  - tutorial 
  - study1_binary_search
  - study2_sort
  - study3_hash
  - study4_encrypt
  - study5_bit
  - study6_graph